In [11]:
import cv2
dog = "image/dog.jpg"

In [36]:
img = cv2.imread("image/dog.jpg")
print(img)

[[[ 81  85  90]
  [ 81  85  90]
  [ 77  83  90]
  ...
  [ 74 113 157]
  [ 74 113 157]
  [ 73 112 156]]

 [[ 81  85  90]
  [ 81  85  90]
  [ 77  83  90]
  ...
  [ 71 110 154]
  [ 70 109 153]
  [ 69 108 152]]

 [[ 81  85  90]
  [ 81  85  90]
  [ 77  83  90]
  ...
  [ 66 105 149]
  [ 65 104 148]
  [ 65 104 148]]

 ...

 [[163 189 206]
  [163 189 206]
  [163 189 206]
  ...
  [170 191 206]
  [170 191 206]
  [170 191 206]]

 [[163 189 206]
  [163 189 206]
  [163 189 206]
  ...
  [170 191 206]
  [170 191 206]
  [170 191 206]]

 [[163 189 206]
  [163 189 206]
  [163 189 206]
  ...
  [170 191 206]
  [170 191 206]
  [170 191 206]]]


In [39]:
cv2.imshow("image",img)
key = cv2.waitKey(0)
print(key)
cv2.destroyAllWindows()

113


In [31]:
img_defult = cv2.imread(dog,cv2.IMREAD_COLOR)
img_gray = cv2.imread(dog,cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread(dog,cv2.IMREAD_UNCHANGED)
cv2.imshow("defult",img_defult)
cv2.imshow("gray",img_gray)
cv2.imshow("unchange",img_unchanged)
key = cv2.waitKey(0)
print(key)
cv2.destroyAllWindows()

-1


In [34]:
img_defult = cv2.imread(dog,cv2.IMREAD_COLOR)
img_gray = cv2.imread(dog,cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread(dog,cv2.IMREAD_UNCHANGED)

height, weight, channel = img_defult.shape
print(height,weight,channel)

428 639 3


In [52]:
cc = cv2.imread("image/dog.jpg")
cv2.imshow("dog",cc)
key = cv2.waitKey(0)
if key == ord("q"):
    cv2.destroyAllWindows()

print(key)

113


In [58]:
gray = cv2.imread("image/dog.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imwrite("output/graydog.jpg",gray)
cv2.imshow("gary",gray)
key = cv2.waitKey(0)
if key == ord("q"):
    cv2.destroyAllWindows()

In [2]:
import cv2
whale = "videos/whale.mp4"

In [4]:
cap = cv2.VideoCapture(whale)

while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        break

    cv2.imshow("video",frame)

    if cv2.waitKey(1) == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


In [2]:
import numpy as np
import cv2

img = np.zeros((460,630,3), dtype= np.uint8)
cv2.imshow("img",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
img = np.zeros((460,630,3), dtype= np.uint8)
img[100:200, 200:300] = (255,255,255)

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
img = np.zeros((460,630,3),dtype = np.uint8)

COLOR = (0,255,255)
THICKNESS = 3

cv2.line(img,(50,100),(400,50),COLOR,THICKNESS,cv2.LINE_4)
cv2.line(img,(50,200),(400,150),COLOR,THICKNESS,cv2.LINE_8)
cv2.line(img,(50,300),(400,250),COLOR,THICKNESS,cv2.LINE_AA)

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cap = cv2.VideoCapture("videos/whale.mp4")

if not cap.isOpened():
    exit()

while True:
    ret , frame = cap.read()

    if not ret:
        break

    resize = cv2.resize(frame,None,fx=1.5,fy=1.5,interpolation=cv2.INTER_AREA)

    cv2.imshow("resize",resize)
    cv2.imshow("frame",frame)
    
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img = cv2.imread("image/dog.jpg")

size_up = cv2.pyrUp(img)
size_down = cv2.pyrDown(img)

cv2.imshow("size_up",size_up)
cv2.imshow("size_down",size_down)
cv2.imshow("original",img)

cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

: 